# Generated by Django 4.2 on 2025-03-13 16:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('request_updation_date', models.DateField(auto_now=True)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('travel_from', models.DateField()),
                ('travel_to', models.DateField()),
                ('preferred_mode_of_travel', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight'), ('Ship', 'Ship')], default='Flight', max_length=30)),
                ('is_lodging_required', models.BooleanField(default=False)),
                ('preferred_lodge', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose_of_travel', models.TextField()),
                ('employee_status', models.CharField(choices=[('applied', 'Applied'), ('canceled', 'Canceled'), ('resubmitted', 'Resubmitted')], default='applied', max_length=15)),
                ('manager_status', models.CharField(choices=[('Requested Edit', 'Requested Edit'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Not Responded', 'Not Responded')], default='Not Responded', max_length=20)),
                ('manager_note', models.TextField(blank=True, null=True)),
                ('manager_additional_request', models.TextField(blank=True, null=True)),
                ('admin_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Requested Info', 'Requested Info')], default='Open', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('employee_response_to_admin', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_app.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_app.manager')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_app.manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
