# Generated by Django 4.2 on 2025-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_app', '0002_ticketrequest_employee_response_to_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='manager_status',
            field=models.CharField(choices=[('Requested Edit', 'Requested Edit'), ('Additional Info', 'Additional Info'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Not Responded', 'Not Responded')], default='Not Responded', max_length=20),
        ),
    ]
